#ifndef _ARDRONE3_SETTINGS_H
#define _ARDRONE3_SETTINGS_H

#define TAG "BebopPiloting"
#define JS_IP_ADDRESS "192.168.42.1"
#define JS_DISCOVERY_PORT 44444
#define JS_C2D_PORT 54321 // should be read from Json
#define JS_D2C_PORT 43210

#define JS_NET_CD_NONACK_ID 10
#define JS_NET_CD_ACK_ID 11
#define JS_NET_DC_NONACK_ID 127
#define JS_NET_DC_ACK_ID 126
#define BD_NET_CD_EMERGENCY_ID 12
#define BD_NET_CD_VIDEO_ACK_ID 13
#define BD_NET_DC_NAVDATA_ID 127
#define BD_NET_DC_EVENT_ID 126
#define BD_NET_DC_VIDEO_DATA_ID 125

#define ERROR_STR_LENGTH 2048

#endif /* _ARDRONE3_SETTINGS_H */